name: Upload File and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: use ssh-key agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.XIA_TEST_ACTION_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.XIA_TEST_ACTION_PRIVATE_KEY }}

      - name: 记录当前推送commit的时间以及commit hash值
        run: |
          echo "COMMIT_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: update github page
        run: |
          echo "current push time is $COMMIT_TIME, current commit hash is $COMMIT_HASH" >> ./docs/index.md
          git config --global user.email "xia@test.com"
          git config --global user.name "xia"
          git add .
          git commit -m "update index.md"
          git push
